<definitions name="INCommunityUpdate" targetNamespace="http://xmlns.oracle.com/CommunityUpdate" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/CommunityUpdate" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:client="http://xmlns.oracle.com/CommunityUpdate"> 
    <types> 
        <schema xmlns="http://www.w3.org/2001/XMLSchema"> 
            <import namespace="http://xmlns.oracle.com/CommunityUpdate" schemaLocation="CommunityUpdate.xsd"/> 
        </schema> 
    </types> 
    <message name="CommunityUpdateRequestMessage"> 
        <part name="payload" element="tns:CommunityUpdateProcessRequest"/> 
    </message> 
    <message name="CommunityUpdateResponseMessage"> 
        <part name="payload" element="tns:CommunityUpdateProcessResponse"/> 
    </message> 
    <portType name="CommunityUpdate"> 
        <operation name="process"> 
            <input message="tns:CommunityUpdateRequestMessage"/> 
            <output message="tns:CommunityUpdateResponseMessage"/> 
        </operation> 
    </portType> 
    <binding name="CommunityUpdateBinding" type="tns:CommunityUpdate"> 
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/> 
        <operation name="process"> 
            <soap:operation style="document" soapAction="process"/> 
            <input> 
                <soap:body use="literal"/> 
            </input> 
            <output> 
                <soap:body use="literal"/> 
            </output> 
        </operation> 
    </binding> 
    <service name="INCommunityUpdate"> 
        <port name="CommunityUpdatePort" binding="tns:CommunityUpdateBinding"> 
            <soap:address location="http://test1:9700/orabpel/default/INCommunityUpdate/1.0"/> 
        </port> 
    </service> 
    <plnk:partnerLinkType name="CommunityUpdate"> 
        <plnk:role name="CommunityUpdateProvider"> 
          <plnk:portType name="tns:CommunityUpdate"/> 
      </plnk:role> 
  </plnk:partnerLinkType> 
</definitions>