<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterErrorMapping/AdapterErrorMapping/AdapterErrorMapping" name="AdapterErrorMapping_db-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="AdapterErrorMapping.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterErrorMapping/AdapterErrorMapping/AdapterErrorMapping"/>
    <wsdl:binding name="AdapterErrorMapping_ptt-binding" type="adap:AdapterErrorMapping_ptt" xmlns:adap="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterErrorMapping/AdapterErrorMapping/AdapterErrorMapping">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="AdapterErrorMappingSelect">
            <soap:operation soapAction="AdapterErrorMappingSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>