<?binding.jca AdapterErrorMapping_db.jca?><wsdl:definitions name="AdapterErrorMapping" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterErrorMapping/AdapterErrorMapping/AdapterErrorMapping" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/AdapterErrorMapping/AdapterErrorMapping/AdapterErrorMapping" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/AdapterErrorMapping">
    <plt:partnerLinkType name="AdapterErrorMapping_plt">
        <plt:role name="AdapterErrorMapping_role">
            <plt:portType name="tns:AdapterErrorMapping_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/AdapterErrorMapping" schemaLocation="xsd/AdapterErrorMapping_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="AdapterErrorMappingSelect_inputParameters">
        <wsdl:part name="AdapterErrorMappingSelect_inputParameters" element="top:AdapterErrorMappingSelect_module_errorCodeInputParameters"/>
    </wsdl:message>
    <wsdl:message name="AdapterErrorMappingCollection_msg">
        <wsdl:part name="AdapterErrorMappingCollection" element="top:AdapterErrorMappingCollection"/>
    </wsdl:message>
    <wsdl:portType name="AdapterErrorMapping_ptt">
        <wsdl:operation name="AdapterErrorMappingSelect">
            <wsdl:input message="tns:AdapterErrorMappingSelect_inputParameters"/>
            <wsdl:output message="tns:AdapterErrorMappingCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>